// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buiyewfwvnpuydzfforc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aXlld2Z3dm5wdXlkemZmb3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjM0ODEsImV4cCI6MjA2NDc5OTQ4MX0.Iz1IHYOAwh2ECFN9YLZT73Qg_dgq61WlbPKfHtAaPGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});